version: '3.1'
volumes:
  gitdata:

services:
  gitea:
    image: gitea/gitea:{{ Env.GITEA_VERSION }}
    # env_file: .env
    ports:
      - {{gcp.Meta "network-interfaces/0/ip"}}:3000
    restart: always
    networks:
      - gitea
    volumes:
      - gitdata:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  gitea: 

